# redis-server.yml
version: "3.7"
services:
  redis:
    image: redis:alpine
    command: redis-server --port 6379
    container_name: redis_boot
    hostname: redis_boot
    restart: always
    labels:
      - "name=redis"
      - "mode=standalone"
    ports:
      - 6378:6379
  mysql:
    # platform: linux/x86_64
    image: mysql:8.0
    container_name: mysql8
    restart: always
    cap_add:
      - SYS_NICE
    ports:
      - 3309:3306
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      TZ: Asia/Seoul
    env_file:
      - ./.env
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --default-authentication-plugin=mysql_native_password
      - --sql-mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
    # volumes:
    #   - ./db:/var/lib/mysql
    #   - ./config:/etc/mysql
    #   - ./mysql-files:/var/lib/mysql-files
